steps:
    - name: 'gcr.io/cloud-builders/docker'
      dir:  'courses/machine_learning/deepdive/06_structured/pipelines/containers/pipeline'   # remove-for-manual
      args: [ 'build', '-t', 'gcr.io/ma-poc-automation/babyweight-pipeline-pipeline:latest', '.' ]
images:
    - 'gcr.io/ma-poc-automation/babyweight-pipeline-pipeline:latest'
